// Regenerates src/public/icons.svg from the full Bootstrap Icons library.
//
// Scans the site for `#bi-{name}` references (in <use href="...#bi-arrow-right">
// and anywhere else) and pulls just those symbols out of the full sprite
// shipped by the bootstrap-icons npm package, so any of the ~2,000 official
// icon names (icons.getbootstrap.com) works by just referencing it — no
// copy-pasting path data.
//
// Run: npm run build:icons
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const SKIP_DIRS = new Set(['node_modules', '.git', 'dist']);
const SCAN_EXTS = new Set(['.html', '.css', '.js', '.mjs']);
const SPRITE_SRC = join(root, 'node_modules/bootstrap-icons/bootstrap-icons.svg');
const SPRITE_OUT = join(root, 'src/public/icons.svg');
const OUT_MARKER = 'src/public/icons.svg'; // skip the generated file itself when scanning

function walk(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) walk(full, files);
    else if (SCAN_EXTS.has(extname(entry)) && !full.endsWith(OUT_MARKER)) files.push(full);
  }
  return files;
}

const used = new Set();
for (const file of walk(root)) {
  const text = readFileSync(file, 'utf8');
  for (const m of text.matchAll(/#bi-([a-z0-9-]+)/g)) used.add(m[1]);
}

if (used.size === 0) {
  console.log('No #bi-{name} references found — nothing to build.');
  process.exit(0);
}

const spriteSource = readFileSync(SPRITE_SRC, 'utf8');
const symbols = new Map();
for (const m of spriteSource.matchAll(/<symbol\b([^>]*)>([\s\S]*?)<\/symbol>/g)) {
  const attrs = m[1];
  const idMatch = attrs.match(/\bid="([a-z0-9-]+)"/);
  const viewBoxMatch = attrs.match(/\bviewBox="([^"]+)"/);
  if (!idMatch) continue;
  symbols.set(idMatch[1], { viewBox: viewBoxMatch ? viewBoxMatch[1] : '0 0 16 16', body: m[2].trim() });
}

const missing = [];
const found = [];
for (const name of [...used].sort()) {
  const symbol = symbols.get(name);
  if (!symbol) { missing.push(name); continue; }
  found.push(`  <symbol id="bi-${name}" viewBox="${symbol.viewBox}">${symbol.body}</symbol>`);
}

if (missing.length) {
  console.error(`Icon name(s) not found in bootstrap-icons: ${missing.join(', ')}`);
  console.error('Check the exact name at https://icons.getbootstrap.com');
  process.exit(1);
}

const output = `<!--
  icons.svg — Bootstrap Icons sprite (https://icons.getbootstrap.com/)
  MIT licensed, https://github.com/twbs/icons/blob/main/LICENSE.md

  GENERATED FILE — do not hand-edit. Regenerated by tools/build-icons.mjs
  from node_modules/bootstrap-icons, pulling only the icons referenced as
  #bi-{name} anywhere in the site. Run: npm run build:icons

  Usage: <svg class="icon" aria-hidden="true"><use href="../src/public/icons.svg#bi-arrow-right"><\\/use><\\/svg>

  (closing tags above are backslash-escaped on purpose: some dev servers,
  e.g. VS Code's Live Server, inject a reload script by naively matching
  the first literal closing tag anywhere in a response body, even inside
  a comment. An unescaped example here previously got spliced with that
  injected script, corrupting the real sprite below it.)

  To use a new icon: write the <use> tag with any name from
  icons.getbootstrap.com, then run \`npm run build:icons\`.
-->
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
${found.join('\n')}
</svg>
`;

writeFileSync(SPRITE_OUT, output);
console.log(`Wrote ${found.length} icon(s) to src/public/icons.svg: ${[...used].sort().join(', ')}`);
